# Importing the neccesary library


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import joblib as jl
%matplotlib inline 

#  Exploring the  data

In [2]:
phish = pd.read_csv('dataset.csv')


In [3]:
phish.head()

having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                 -1           1                   1                 1   
1                  1           1                   1                 1   
2                  1           0                   1                 1   
3                  1           0                   1                 1   
4                  1           0                  -1                 1   

   double_slash_redirecting  Prefix_Suffix   having_Sub_Domain  \
0                        -1              -1                 -1   
1                         1              -1                  0   
2                         1              -1                 -1   
3                         1              -1                 -1   
4                         1              -1                  1   

   SSLfinal_State  Domain_registeration_length  Favicon   ...    popUpWindow  \
0              -1                           -1        1   ...              1   
1               1                           -1        1   ...              1   
2              -1                           -1        1   ...              1   
3              -1                            1        1   ...              1   
4               1                           -1        1   ...             -1   

   Iframe  age_of_domain   DNSRecord   web_traffic  Page_Rank  Google_Index  \
0       1              -1          -1           -1         -1             1   
1       1              -1          -1            0         -1             1   
2       1               1          -1            1         -1             1   
3       1              -1          -1            1         -1             1   
4       1              -1          -1            0         -1             1   

   Links_pointing_to_page  Statistical_report  Result  
0                       1                  -1      -1  
1                       1                   1      -1  
2                       0                  -1      -1  
3                      -1                   1      -1  
4                       1                   1       1  

[5 rows x 31 columns]

In [4]:
phish.describe()

having_IP_Address    URL_Length  Shortining_Service  having_At_Symbol  \
count       11055.000000  11055.000000        11055.000000      11055.000000   
mean            0.313795     -0.633198            0.738761          0.700588   
std             0.949534      0.766095            0.673998          0.713598   
min            -1.000000     -1.000000           -1.000000         -1.000000   
25%            -1.000000     -1.000000            1.000000          1.000000   
50%             1.000000     -1.000000            1.000000          1.000000   
75%             1.000000     -1.000000            1.000000          1.000000   
max             1.000000      1.000000            1.000000          1.000000   

       double_slash_redirecting  Prefix_Suffix   having_Sub_Domain  \
count              11055.000000    11055.000000       11055.000000   
mean                   0.741474       -0.734962           0.063953   
std                    0.671011        0.678139           0.817518   
min                   -1.000000       -1.000000          -1.000000   
25%                    1.000000       -1.000000          -1.000000   
50%                    1.000000       -1.000000           0.000000   
75%                    1.000000       -1.000000           1.000000   
max                    1.000000        1.000000           1.000000   

       SSLfinal_State  Domain_registeration_length       Favicon  \
count    11055.000000                 11055.000000  11055.000000   
mean         0.250927                    -0.336771      0.628584   
std          0.911892                     0.941629      0.777777   
min         -1.000000                    -1.000000     -1.000000   
25%         -1.000000                    -1.000000      1.000000   
50%          1.000000                    -1.000000      1.000000   
75%          1.000000                     1.000000      1.000000   
max          1.000000                     1.000000      1.000000   

           ...        popUpWindow        Iframe  age_of_domain     DNSRecord   \
count      ...       11055.000000  11055.000000    11055.000000  11055.000000   
mean       ...           0.613388      0.816915        0.061239      0.377114   
std        ...           0.789818      0.576784        0.998168      0.926209   
min        ...          -1.000000     -1.000000       -1.000000     -1.000000   
25%        ...           1.000000      1.000000       -1.000000     -1.000000   
50%        ...           1.000000      1.000000        1.000000      1.000000   
75%        ...           1.000000      1.000000        1.000000      1.000000   
max        ...           1.000000      1.000000        1.000000      1.000000   

        web_traffic     Page_Rank  Google_Index  Links_pointing_to_page  \
count  11055.000000  11055.000000  11055.000000            11055.000000   
mean       0.287291     -0.483673      0.721574                0.344007   
std        0.827733      0.875289      0.692369                0.569944   
min       -1.000000     -1.000000     -1.000000               -1.000000   
25%        0.000000     -1.000000      1.000000                0.000000   
50%        1.000000     -1.000000      1.000000                0.000000   
75%        1.000000      1.000000      1.000000                1.000000   
max        1.000000      1.000000      1.000000                1.000000   

       Statistical_report        Result  
count        11055.000000  11055.000000  
mean             0.719584      0.113885  
std              0.694437      0.993539  
min             -1.000000     -1.000000  
25%              1.000000     -1.000000  
50%              1.000000      1.000000  
75%              1.000000      1.000000  
max              1.000000      1.000000  

[8 rows x 31 columns]

In [5]:
phish.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 31 columns):
having_IP_Address              11055 non-null int64
URL_Length                     11055 non-null int64
Shortining_Service             11055 non-null int64
having_At_Symbol               11055 non-null int64
double_slash_redirecting       11055 non-null int64
Prefix_Suffix                  11055 non-null int64
having_Sub_Domain              11055 non-null int64
SSLfinal_State                 11055 non-null int64
Domain_registeration_length    11055 non-null int64
Favicon                        11055 non-null int64
port                           11055 non-null int64
HTTPS_token                    11055 non-null int64
Request_URL                    11055 non-null int64
URL_of_Anchor                  11055 non-null int64
Links_in_tags                  11055 non-null int64
SFH                            11055 non-null int64
Submitting_to_email            11055 non-null int64
Abnorma

In [6]:
phish.isnull().sum()

having_IP_Address              0
URL_Length                     0
Shortining_Service             0
having_At_Symbol               0
double_slash_redirecting       0
Prefix_Suffix                  0
having_Sub_Domain              0
SSLfinal_State                 0
Domain_registeration_length    0
Favicon                        0
port                           0
HTTPS_token                    0
Request_URL                    0
URL_of_Anchor                  0
Links_in_tags                  0
SFH                            0
Submitting_to_email            0
Abnormal_URL                   0
Redirect                       0
on_mouseover                   0
RightClick                     0
popUpWindow                    0
Iframe                         0
age_of_domain                  0
DNSRecord                      0
web_traffic                    0
Page_Rank                      0
Google_Index                   0
Links_pointing_to_page         0
Statistical_report             0
Result    

In [7]:
#from sklearn.decomposition import PCA

# Model Building

In [8]:
from sklearn.model_selection import train_test_split
#Splitting the data into test and train
X_train, X_test, y_train, y_test = train_test_split(phish.drop('Result',axis=1),phish['Result'], test_size=0.30, random_state=0)

In [9]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [10]:
predictions = logmodel.predict(X_test)

In [11]:
from sklearn.metrics import classification_report

In [12]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

         -1       0.93      0.90      0.91      1498
          1       0.92      0.95      0.93      1819

avg / total       0.92      0.92      0.92      3317



In [13]:
features = phish.columns
features

Index(['having_IP_Address', 'URL_Length', 'Shortining_Service',
       'having_At_Symbol', 'double_slash_redirecting', 'Prefix_Suffix ',
       'having_Sub_Domain', 'SSLfinal_State', 'Domain_registeration_length',
       'Favicon', 'port', 'HTTPS_token', 'Request_URL', 'URL_of_Anchor',
       'Links_in_tags', 'SFH', 'Submitting_to_email', 'Abnormal_URL',
       'Redirect', 'on_mouseover', 'RightClick', 'popUpWindow', 'Iframe',
       'age_of_domain ', 'DNSRecord ', 'web_traffic', 'Page_Rank',
       'Google_Index', 'Links_pointing_to_page', 'Statistical_report',
       'Result'],
      dtype='object')

In [14]:
X_train, X_test, y_train, y_test = train_test_split(phish.drop('Result',axis=1),phish['Result'], test_size=0.30,random_state=1)

In [15]:
from sklearn.svm import SVC
model = SVC()

In [16]:
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [17]:
predictions = model.predict(X_test)

In [18]:
from sklearn.metrics import classification_report,confusion_matrix

In [19]:
print(confusion_matrix(y_test,predictions))

[[1358  132]
 [  66 1761]]


In [20]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

         -1       0.95      0.91      0.93      1490
          1       0.93      0.96      0.95      1827

avg / total       0.94      0.94      0.94      3317



In [21]:
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']} 

In [22]:
from sklearn.model_selection import GridSearchCV

In [23]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)

In [24]:

grid.fit(X_train,y_train)

Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.5701550387596899, total=   9.6s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   14.5s remaining:    0.0s


[CV]  C=0.1, gamma=1, kernel=rbf, score=0.5684373788290035, total=   9.3s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   29.2s remaining:    0.0s


[CV]  C=0.1, gamma=1, kernel=rbf, score=0.5692128732066692, total=  11.5s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.9259689922480621, total=   4.3s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.9352462194649089, total=   4.6s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.9278790228770841, total=   4.3s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV]  C=0.1, gamma=0.01, kernel=rbf, score=0.9108527131782945, total=   3.9s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV]  C=0.1, gamma=0.01, kernel=rbf, score=0.9247770453664211, total=   3.8s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV]  C=0.1, gamma=0.01, kernel=rbf, score=0.9224505622334238, total=   3.5s
[CV] C=0.1, gamma=0.001, kernel=rbf .....

[CV]  C=100, gamma=0.0001, kernel=rbf, score=0.9329197363319116, total=   1.9s
[CV] C=100, gamma=0.0001, kernel=rbf .................................
[CV]  C=100, gamma=0.0001, kernel=rbf, score=0.925164792555254, total=   1.9s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV] .......... C=1000, gamma=1, kernel=rbf, score=0.85, total=   6.6s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV]  C=1000, gamma=1, kernel=rbf, score=0.8487785963551764, total=   6.6s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV]  C=1000, gamma=1, kernel=rbf, score=0.8627374951531601, total=   6.9s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.9589147286821705, total=   2.8s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.9592865451725475, total=   2.8s
[CV] C=1000, gamma=0.1, kernel=rbf .......

[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed:  8.1min finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [25]:
grid.best_params_

{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}

In [26]:
grid.best_estimator_

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [27]:
grid_predictions = grid.predict(X_test)

In [28]:
print(confusion_matrix(y_test,grid_predictions))

[[1401   89]
 [  35 1792]]


In [29]:
print(classification_report(y_test,grid_predictions))

             precision    recall  f1-score   support

         -1       0.98      0.94      0.96      1490
          1       0.95      0.98      0.97      1827

avg / total       0.96      0.96      0.96      3317



In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [45]:
fit_model = knn.fit(X_train,y_train)

In [43]:
knn.predict(X_test)

array([-1,  1,  1, ...,  1,  1, -1])

In [50]:
fit_model.score(X_test, y_test)

0.9499547784142297

In [51]:
print(confusion_matrix(y_test,pred))

[[1400   90]
 [  76 1751]]


In [52]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

         -1       0.95      0.94      0.94      1490
          1       0.95      0.96      0.95      1827

avg / total       0.95      0.95      0.95      3317



In [53]:
#error_rate = []

# Will take some time
#for i in range(1,500):
    
 #   knn = KNeighborsClassifier(n_neighbors=i)
  #  knn.fit(X_train,y_train)
   # pred_i = knn.predict(X_test)
    #error_rate.append(np.mean(pred_i != y_test))

In [54]:
#plt.figure(figsize=(10,6))
#plt.plot(range(1,40),error_rate,color='blue', linestyle='dashed', marker='o',
 #        markerfacecolor='red', markersize=10)
#plt.title('Error Rate vs. K Value')
#plt.xlabel('K')
#plt.ylabel('Error Rate')

In [55]:
jl.dump(fit_model,'phishnot.pkl')

['phishnot.pkl']

In [57]:
jl.load('phishnot.pkl')

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')